services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54333:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 60s
      retries: 60
  db-init:
    image: alpine/psql
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGPORT: 5432
      PGHOST: db
    depends_on:
      db:
        condition: service_healthy
    command: ["-c", "create table if not exists thing(id uuid not null, thing_val int not null);"]
volumes:
  postgres_data:
