micronaut:
  application:
    name: sampleNewrelicKotlinFailure
  http:
    services:
      poke-api:
        url: "https://pokeapi.co"
#  metrics:
#    enabled: true
#    export:
#      otlp:
#        enabled: true
#        url: https://otlp.nr-data.net:4318/v1/metrics
#        aggregationTemporality: delta
#        headers: api-key=${NEW_RELIC_LICENSE_KEY}
#    binders:
#      r2dbc:
#        observation:
#          enabled: true
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${PGUSER:postgres}@${PGHOST:localhost}:${PGPORT:54333}/${PGDATABASE:postgres}
      password: ${PGPASSWORD:password}
#otel:
#  service:
#    name: sample-newrelic-kotlin-failure-ajh
#  traces:
#    exporter: otlp
#    exclusions: /health
#  metrics:
#    default_histogram_aggregation: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
#    exporter: otlp
#  logs:
#    exporter: otlp
#  exporter:
#    otlp:
#      endpoint: https://otlp.nr-data.net
#      headers: api-key=${NEW_RELIC_LICENSE_KEY}
#      compression: gzip
#      protocol: http/protobuf
#      metrics_temporality_preference: delta
